#pragma once
#include <d2d1.h>
#include <d2d1effects.h>

namespace suku
{
	enum class EffectScaleMode
	{
		NearestNeighbor = D2D1_2DAFFINETRANSFORM_INTERPOLATION_MODE_NEAREST_NEIGHBOR,
		Linear = D2D1_2DAFFINETRANSFORM_INTERPOLATION_MODE_LINEAR,
		Cubic = D2D1_2DAFFINETRANSFORM_INTERPOLATION_MODE_CUBIC,
		MultiSampleLinear = D2D1_2DAFFINETRANSFORM_INTERPOLATION_MODE_MULTI_SAMPLE_LINEAR,
		Anisotropic = D2D1_2DAFFINETRANSFORM_INTERPOLATION_MODE_ANISOTROPIC,
		HighQualityCubic = D2D1_2DAFFINETRANSFORM_INTERPOLATION_MODE_HIGH_QUALITY_CUBIC
	};

	enum class BitmapScaleMode
	{
		NearestNeighbor = D2D1_BITMAP_INTERPOLATION_MODE_NEAREST_NEIGHBOR,
		Linear = D2D1_BITMAP_INTERPOLATION_MODE_LINEAR,
	};
}