#pragma once

#include "targetver.h"
#define WIN32_LEAN_AND_MEAN
// Windows
#define NOMINMAX
#include <d2d1.h>
#include <mmsystem.h>
#include <windows.h>
#include <wincodec.h>
#include <wrl.h>
// C++
#include <cstdlib>
#include <cstring>
#include <cmath>
#include <ctime>
#include <initializer_list>
#include <random>
#include <string>
#include <thread>
#include <mutex>
