#pragma comment (lib, "d2d1")
#pragma comment (lib, "dxguid.lib")
#pragma comment (lib, "winmm.lib")
// for sound (XAudio2 & Media Foundation)
#pragma comment (lib, "xaudio2.lib")
#pragma comment (lib, "mfplat.lib")
#pragma comment (lib, "mfreadwrite.lib")
#pragma comment (lib, "mf.lib")
#pragma comment (lib, "mfuuid.lib")
#pragma comment (lib, "ole32.lib")
#pragma comment (lib, "propsys.lib")